name = "HAS Client Pack"
author = "Darkblade360350"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5478e79f64c5afeb3dee02b55c93ae8679dd4efedb288655194c2243006a8498"

[versions]
fabric = "0.14.8"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19"]
