name = "Hunters Among Speedrunners Client Pack"
author = "Darkblade360350"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0188554997042daa25c6a43e5e37e1d6f956887d6d6105bb82f910f69cb67151"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
