name = "Hunters Among Speedrunners Client Pack"
author = "Darkblade360350"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0243e9db8ef3314287c375c87568db2d73fa25e0b0a2492bc79ea3eabb2da2bb"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
