name = "HAS Client Pack"
author = "Darkblade360350"
version = "3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8044e6e2ec3266e1931cf04211c196b07b28cc047fc284010b4842c0798069e3"

[versions]
fabric = "0.14.8"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19"]
